# Config file
# second digit in array is the memory address of the omron
# memory address in the omron starts at %0

air_conditioner_runtime:        [0,0,0]
auto_grease_hours:              [0,1,0]
brake_pressure:                 [0,2,0]
brake_applications:             [0,3,0]
broom_runtime:                  [0,4,0]
clamp_closed:                   [0,5,0]
conveyor_runtime:               [0,6,0]
distance_travelled:             [0,7,0]
distance_travelled_work:        [0,8,0]
genset_hours:                   [0,9,0]
impact_force:                   [0,10,0]
machine_braking_performance:    [0,11,0]
machine_work_hours:             [0,12,0]
main_engine_hours:              [0,13,0]
pressure:                       [0,14,0]
pressure_differential:          [0,15,0]
pressure_per_minute:            [0,16,0]
temperature:                    [0,17,0]
trolley_operational_hours:      [0,18,0]
voltage_output_alternator:      [0,19,0]
windscreen_wiper_runtime:       [0,20,0]
workhead_insertions:            [0,21,0]
time_stamp: 0
