FRONT_TROLLEY_ENCODER_POSITION:       0
DRIVE_HOURS:                          0
ENGINE_HOURS:                         0
HYD_ON_HOURS:                         0
GREASE_HOURS:                         0
IMC_ALC_SYNC_ACK:                     0
IMC_ALC_SUPER_VALUE:                  0
IMC_ALC_LINE_VALUE:                   0
IMC_ALC_LOCATION_METERS:              0
IMC_ALC_SYNC_PRESSED:                 0
HOURS_COUNT:                          0
WORK_DRIVE_HOURS:                     0
IMC_ALC_LIFT_VALUE:                   0
IMC_ALC_BUZZER_OUT:                   0
BRAKE_APPLICATIONS:                   0
IMC_ALC_VERSINE_VALUE:                0
IMC_ALC_BUZZER_MUTE:                  0
IMC_ALC_BUZZER_MUTE_ACK:              0
IMC_ALC_BUZZER_TRIGGER:               0
IMC_ALC_CONNECTED:                    0
IMC_ALC_BUZZER_OFF:                   0
