AUTO_CYCLE_KEEP: 0
WORK_PENDULUM_CAL: 0
LH_HEIGHT_POT_CAL: 0
RH_HEIGHT_POT_CAL: 0
VERSINE_OFFSET: 0
ALC_LIFT_OFFSET_CAL: 0
ALC_LINE_CAL: 0
ALC_SUPER_CAL: 0
ALC_VERSINE_CAL: 0
WORK_DRIVE_HOURS: 0
IMC_ALC_VERSINE_VALUE: 0
IMC_ALC_SYNC_PRESSED: 0
IMC_ALC_SYNC_ACK: 0
IMC_ALC_SUPER_VALUE: 0
IMC_ALC_LOCATION_METERS: 0
IMC_ALC_LIFT_VALUE: 0
IMC_ALC_CONNECTED: 0
IMC_ALC_BUZZER_TRIGGER: 0
IMC_ALC_BUZZER_OUT: 0
IMC_ALC_LINE_VALUE: 0
IMC_ALC_BUZZER_MUTE_ACK: 0
IMC_ALC_BUZZER_MUTE: 0
HYD_ON_HOURS: 0
HOURS_COUNT: 0
GREASE_HOURS: 0
FUEL_LEVEL: 0
FRONT_TROLLEY_ENCODER_POSITION: 0
ENGINE_HOURS: 0
DRIVE_HOURS: 0
BRAKE_APPLICATIONS: 0
